import { BuildingModel, PaperComponent } from '../types';

// Export building as Wavefront .OBJ + .MTL format
export function exportToOBJ(building: BuildingModel): { objContent: string; mtlContent: string } {
  let obj = `# Wavefront OBJ generated by Interactive 3D Urban Resilience & Disaster Simulation\n`;
  obj += `# Model: ${building.name}\n`;
  obj += `# Components: ${building.components.length}\n`;
  obj += `mtllib ${building.name.toLowerCase().replace(/\s+/g, '_')}.mtl\n\n`;

  let mtl = `# Wavefront MTL Material Library\n\n`;
  const materialsDefined = new Set<string>();

  let vertexOffset = 1;
  let uvOffset = 1;
  let normalOffset = 1;

  building.components.forEach((comp, compIdx) => {
    const matName = `mat_${comp.materialConfig.id || 'default'}`;
    if (!materialsDefined.has(matName)) {
      materialsDefined.add(matName);
      mtl += `newmtl ${matName}\n`;
      mtl += `Ka 0.2 0.2 0.2\n`;
      mtl += `Kd 0.8 0.8 0.8\n`;
      mtl += `Ks 0.1 0.1 0.1\n`;
      mtl += `Ns 10.0\n`;
      mtl += `d 1.0\n`;
      mtl += `illum 2\n\n`;
    }

    obj += `o Component_${compIdx}_${comp.shape}\n`;
    obj += `usemtl ${matName}\n`;

    const [px, py, pz] = comp.position;
    const [sx, sy, sz] = comp.scale;
    const hx = sx / 2;
    const hy = sy / 2;
    const hz = sz / 2;

    // 8 Box Vertices
    const rawVertices = [
      [-hx, -hy, -hz],
      [hx, -hy, -hz],
      [hx, hy, -hz],
      [-hx, hy, -hz],
      [-hx, -hy, hz],
      [hx, -hy, hz],
      [hx, hy, hz],
      [-hx, hy, hz],
    ];

    // Simple rotation handling around Y
    const ry = comp.rotation[1];
    const cosY = Math.cos(ry);
    const sinY = Math.sin(ry);

    rawVertices.forEach(([vx, vy, vz]) => {
      const rx = vx * cosY + vz * sinY;
      const rz = -vx * sinY + vz * cosY;
      obj += `v ${(px + rx).toFixed(4)} ${(py + vy).toFixed(4)} ${(pz + rz).toFixed(4)}\n`;
    });

    // UVs
    obj += `vt 0.0 0.0\n`;
    obj += `vt 1.0 0.0\n`;
    obj += `vt 1.0 1.0\n`;
    obj += `vt 0.0 1.0\n`;

    // Normals (Front, Back, Top, Bottom, Right, Left)
    obj += `vn 0.0 0.0 1.0\n`;
    obj += `vn 0.0 0.0 -1.0\n`;
    obj += `vn 0.0 1.0 0.0\n`;
    obj += `vn 0.0 -1.0 0.0\n`;
    obj += `vn 1.0 0.0 0.0\n`;
    obj += `vn -1.0 0.0 0.0\n`;

    const vo = vertexOffset;
    const uvo = uvOffset;
    const no = normalOffset;

    // 6 Faces (quads expressed as triangles)
    // Front (5,6,7,8)
    obj += `f ${vo+4}/${uvo}/${no} ${vo+5}/${uvo+1}/${no} ${vo+6}/${uvo+2}/${no}\n`;
    obj += `f ${vo+4}/${uvo}/${no} ${vo+6}/${uvo+2}/${no} ${vo+7}/${uvo+3}/${no}\n`;
    // Back (2,1,4,3)
    obj += `f ${vo+1}/${uvo}/${no+1} ${vo}/${uvo+1}/${no+1} ${vo+3}/${uvo+2}/${no+1}\n`;
    obj += `f ${vo+1}/${uvo}/${no+1} ${vo+3}/${uvo+2}/${no+1} ${vo+2}/${uvo+3}/${no+1}\n`;
    // Top (4,3,7,8)
    obj += `f ${vo+3}/${uvo}/${no+2} ${vo+2}/${uvo+1}/${no+2} ${vo+6}/${uvo+2}/${no+2}\n`;
    obj += `f ${vo+3}/${uvo}/${no+2} ${vo+6}/${uvo+2}/${no+2} ${vo+7}/${uvo+3}/${no+2}\n`;
    // Bottom (1,2,6,5)
    obj += `f ${vo}/${uvo}/${no+3} ${vo+1}/${uvo+1}/${no+3} ${vo+5}/${uvo+2}/${no+3}\n`;
    obj += `f ${vo}/${uvo}/${no+3} ${vo+5}/${uvo+2}/${no+3} ${vo+4}/${uvo+3}/${no+3}\n`;
    // Right (2,3,7,6)
    obj += `f ${vo+1}/${uvo}/${no+4} ${vo+2}/${uvo+1}/${no+4} ${vo+6}/${uvo+2}/${no+4}\n`;
    obj += `f ${vo+1}/${uvo}/${no+4} ${vo+6}/${uvo+2}/${no+4} ${vo+5}/${uvo+3}/${no+4}\n`;
    // Left (1,4,8,5)
    obj += `f ${vo}/${uvo}/${no+5} ${vo+4}/${uvo+1}/${no+5} ${vo+7}/${uvo+2}/${no+5}\n`;
    obj += `f ${vo}/${uvo}/${no+5} ${vo+7}/${uvo+2}/${no+5} ${vo+3}/${uvo+3}/${no+5}\n`;

    vertexOffset += 8;
    uvOffset += 4;
    normalOffset += 6;
  });

  return { objContent: obj, mtlContent: mtl };
}

// Export as standard GLTF 2.0 JSON format
export function exportToGLTF(building: BuildingModel): string {
  const gltf = {
    asset: {
      version: '2.0',
      generator: 'Interactive 3D Urban Resilience Studio',
    },
    scene: 0,
    scenes: [
      {
        name: building.name,
        nodes: building.components.map((_, i) => i),
      },
    ],
    nodes: building.components.map((comp, idx) => ({
      name: `${comp.name}_${idx}`,
      translation: comp.position,
      rotation: [0, Math.sin(comp.rotation[1] / 2), 0, Math.cos(comp.rotation[1] / 2)],
      scale: comp.scale,
      mesh: 0,
    })),
    meshes: [
      {
        name: 'PaperBlockMesh',
        primitives: [
          {
            attributes: {
              POSITION: 0,
              NORMAL: 1,
            },
            indices: 2,
            material: 0,
          },
        ],
      },
    ],
    materials: [
      {
        name: 'PapercraftMaterial',
        pbrMetallicRoughness: {
          baseColorFactor: [0.95, 0.93, 0.9, 1.0],
          metallicFactor: 0.05,
          roughnessFactor: 0.8,
        },
      },
    ],
    accessors: [
      {
        bufferView: 0,
        componentType: 5126,
        count: 24,
        type: 'VEC3',
        max: [0.5, 0.5, 0.5],
        min: [-0.5, -0.5, -0.5],
      },
      {
        bufferView: 1,
        componentType: 5126,
        count: 24,
        type: 'VEC3',
      },
      {
        bufferView: 2,
        componentType: 5123,
        count: 36,
        type: 'SCALAR',
      },
    ],
  };

  return JSON.stringify(gltf, null, 2);
}

// Export as 3D-printable STL (ASCII)
export function exportToSTL(building: BuildingModel): string {
  let stl = `solid ${building.name.replace(/[^a-zA-Z0-9]/g, '_')}\n`;

  building.components.forEach((comp) => {
    const [px, py, pz] = comp.position;
    const [sx, sy, sz] = comp.scale;
    const hx = sx / 2;
    const hy = sy / 2;
    const hz = sz / 2;

    const vertices = [
      [px - hx, py - hy, pz - hz],
      [px + hx, py - hy, pz - hz],
      [px + hx, py + hy, pz - hz],
      [px - hx, py + hy, pz - hz],
      [px - hx, py - hy, pz + hz],
      [px + hx, py - hy, pz + hz],
      [px + hx, py + hy, pz + hz],
      [px - hx, py + hy, pz + hz],
    ];

    const addFacet = (v1: number[], v2: number[], v3: number[], normal: [number, number, number]) => {
      stl += `  facet normal ${normal[0]} ${normal[1]} ${normal[2]}\n`;
      stl += `    outer loop\n`;
      stl += `      vertex ${v1[0].toFixed(3)} ${v1[1].toFixed(3)} ${v1[2].toFixed(3)}\n`;
      stl += `      vertex ${v2[0].toFixed(3)} ${v2[1].toFixed(3)} ${v2[2].toFixed(3)}\n`;
      stl += `      vertex ${v3[0].toFixed(3)} ${v3[1].toFixed(3)} ${v3[2].toFixed(3)}\n`;
      stl += `    endloop\n`;
      stl += `  endfacet\n`;
    };

    // 12 Triangles for 6 faces
    addFacet(vertices[4], vertices[5], vertices[6], [0, 0, 1]);
    addFacet(vertices[4], vertices[6], vertices[7], [0, 0, 1]);

    addFacet(vertices[1], vertices[0], vertices[3], [0, 0, -1]);
    addFacet(vertices[1], vertices[3], vertices[2], [0, 0, -1]);

    addFacet(vertices[3], vertices[2], vertices[6], [0, 1, 0]);
    addFacet(vertices[3], vertices[6], vertices[7], [0, 1, 0]);

    addFacet(vertices[0], vertices[1], vertices[5], [0, -1, 0]);
    addFacet(vertices[0], vertices[5], vertices[4], [0, -1, 0]);

    addFacet(vertices[1], vertices[2], vertices[6], [1, 0, 0]);
    addFacet(vertices[1], vertices[6], vertices[5], [1, 0, 0]);

    addFacet(vertices[0], vertices[4], vertices[7], [-1, 0, 0]);
    addFacet(vertices[0], vertices[7], vertices[3], [-1, 0, 0]);
  });

  stl += `endsolid ${building.name.replace(/[^a-zA-Z0-9]/g, '_')}\n`;
  return stl;
}

// Generate Printable DIY Papercraft Net (SVG Net with Glue Tabs & Score Lines, like e.jfif)
export function generatePapercraftPrintableSVG(building: BuildingModel): string {
  const width = 1200;
  const height = 900;

  let svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${width} ${height}" width="${width}" height="${height}" style="background-color: #fdfbf7;">\n`;
  
  // Header with instructions matching e.jfif
  svg += `  <style>
    .title { font-family: 'Helvetica Neue', Arial, sans-serif; font-size: 22px; font-weight: bold; fill: #1e293b; }
    .subtitle { font-family: 'Helvetica Neue', Arial, sans-serif; font-size: 13px; fill: #64748b; }
    .cut-line { stroke: #0f172a; stroke-width: 1.5; fill: none; }
    .fold-line { stroke: #94a3b8; stroke-width: 1.2; stroke-dasharray: 4,4; fill: none; }
    .tab { fill: #f1f5f9; stroke: #94a3b8; stroke-width: 1; stroke-dasharray: 2,2; }
    .tab-text { font-family: sans-serif; font-size: 9px; fill: #94a3b8; text-anchor: middle; }
    .window-rect { fill: #cbd5e1; stroke: #475569; stroke-width: 1; }
    .legend-box { fill: #ffffff; stroke: #e2e8f0; stroke-width: 1; rx: 4; }
  </style>\n`;

  // Cutting mat guide background
  svg += `  <!-- Grid lines -->\n`;
  for (let x = 40; x < width - 40; x += 40) {
    svg += `  <line x1="${x}" y1="80" x2="${x}" y2="${height - 40}" stroke="#f1f5f9" stroke-width="0.75" />\n`;
  }
  for (let y = 80; y < height - 40; y += 40) {
    svg += `  <line x1="40" y1="${y}" x2="${width - 40}" y2="${y}" stroke="#f1f5f9" stroke-width="0.75" />\n`;
  }

  // Header Banner
  svg += `  <text x="50" y="45" class="title">${building.name.toUpperCase()} — DIY URBAN PAPERCRAFT TEMPLATE</text>\n`;
  svg += `  <text x="50" y="65" class="subtitle">1:100 Architectural Scale · Solid Lines = Cut (✂️) · Dashed Lines = Mountain Fold (▲) · Glue Tabs = Apply Paste</text>\n`;

  // Draw printable unfolds for each primary component
  let startX = 70;
  let startY = 120;

  building.components.slice(0, 4).forEach((comp, idx) => {
    const scaleFactor = 45; // mm per meter
    const w = Math.max(30, comp.scale[0] * scaleFactor);
    const h = Math.max(50, comp.scale[1] * scaleFactor);
    const d = Math.max(30, comp.scale[2] * scaleFactor);

    if (startX + (w * 4 + d * 2) > width - 60) {
      startX = 70;
      startY += h + d * 2 + 50;
    }

    const curY = startY + d;
    svg += `  <!-- Component ${idx + 1}: ${comp.name} -->\n`;
    svg += `  <text x="${startX}" y="${startY - 10}" font-family="sans-serif" font-size="12px" font-weight="bold" fill="#334155">Part ${idx + 1}: ${comp.name} (${comp.shape})</text>\n`;

    // 4 Facade walls: Front, Right, Back, Left
    // 1. Front Face
    const x0 = startX;
    svg += `  <rect x="${x0}" y="${curY}" width="${w}" height="${h}" fill="#fdfbf7" class="cut-line" />\n`;
    // Add miniature window details
    for (let r = 0; r < Math.floor(h / 25); r++) {
      for (let c = 0; c < Math.floor(w / 18); c++) {
        svg += `  <rect x="${x0 + 6 + c * 16}" y="${curY + 8 + r * 22}" width="10" height="14" class="window-rect" />\n`;
      }
    }

    // 2. Right Face
    const x1 = x0 + w;
    svg += `  <rect x="${x1}" y="${curY}" width="${d}" height="${h}" fill="#fdfbf7" class="cut-line" />\n`;
    svg += `  <line x1="${x1}" y1="${curY}" x2="${x1}" y2="${curY + h}" class="fold-line" />\n`;

    // 3. Back Face
    const x2 = x1 + d;
    svg += `  <rect x="${x2}" y="${curY}" width="${w}" height="${h}" fill="#fdfbf7" class="cut-line" />\n`;
    svg += `  <line x1="${x2}" y1="${curY}" x2="${x2}" y2="${curY + h}" class="fold-line" />\n`;

    // 4. Left Face
    const x3 = x2 + w;
    svg += `  <rect x="${x3}" y="${curY}" width="${d}" height="${h}" fill="#fdfbf7" class="cut-line" />\n`;
    svg += `  <line x1="${x3}" y1="${curY}" x2="${x3}" y2="${curY + h}" class="fold-line" />\n`;

    // Glue Tab on right side
    const tabW = 16;
    svg += `  <polygon points="${x3 + d},${curY + 6} ${x3 + d + tabW},${curY + 14} ${x3 + d + tabW},${curY + h - 14} ${x3 + d},${curY + h - 6}" class="tab" />\n`;
    svg += `  <text x="${x3 + d + tabW / 2}" y="${curY + h / 2}" class="tab-text" transform="rotate(90 ${x3 + d + tabW / 2} ${curY + h / 2})">GLUE</text>\n`;

    // Top Roof Fold Face
    svg += `  <rect x="${x0}" y="${curY - d}" width="${w}" height="${d}" fill="#faf5ee" class="cut-line" />\n`;
    svg += `  <line x1="${x0}" y1="${curY}" x2="${x0 + w}" y2="${curY}" class="fold-line" />\n`;
    // Roof glue tabs
    svg += `  <polygon points="${x0},${curY - d + 6} ${x0 - 12},${curY - d + 12} ${x0 - 12},${curY - 6} ${x0},${curY}" class="tab" />\n`;
    svg += `  <polygon points="${x0 + w},${curY - d + 6} ${x0 + w + 12},${curY - d + 12} ${x0 + w + 12},${curY - 6} ${x0 + w},${curY}" class="tab" />\n`;

    // Bottom Base Fold Face
    svg += `  <rect x="${x0}" y="${curY + h}" width="${w}" height="${d}" fill="#faf5ee" class="cut-line" />\n`;
    svg += `  <line x1="${x0}" y1="${curY + h}" x2="${x0 + w}" y2="${curY + h}" class="fold-line" />\n`;

    startX += w * 2 + d * 2 + tabW + 60;
  });

  // Footer Legend Box
  svg += `  <g transform="translate(50, ${height - 65})">
    <rect width="400" height="40" class="legend-box" />
    <line x1="20" y1="20" x2="60" y2="20" class="cut-line" />
    <text x="70" y="24" font-family="sans-serif" font-size="11px" fill="#334155">Cut Line (Scissors/Hobby Knife)</text>
    <line x1="220" y1="20" x2="260" y2="20" class="fold-line" />
    <text x="270" y="24" font-family="sans-serif" font-size="11px" fill="#334155">Score &amp; Fold Line</text>
  </g>\n`;

  svg += `</svg>`;
  return svg;
}

// Download helper trigger
export function triggerFileDownload(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
